services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    user: 1000:1000
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: bun run dev
    volumes:
      - ./:/app
