<template>
    <div class="cocktail-print-container">
        <h1>{{ cocktail.name }}</h1>
        <template v-if="cocktail.description">
            <h2>Description:</h2>
            <div v-html="parsedDescription"></div>
        </template>
        <div class="cocktail-print-image" v-if="cocktail.main_image_id">
            <img :src="cocktail.images[0].url" :alt="cocktail.images[0].copyright">
        </div>
        <div class="print-second-row">
            <div class="print-ingredients">
                <h2>Ingredients:</h2>
                <ul>
                    <li v-for="ingredient in cocktail.ingredients">
                        {{ ingredient.amount }} {{ ingredient.units }} &middot; {{ ingredient.name }}
                    </li>
                </ul>
            </div>
            <div class="print-instructions">
                <h2>Instructions:</h2>
                <div v-html="parsedInstructions"></div>
            </div>
        </div>
        <div class="cocktail-print-footer">
            Cocktail recipe generated by Bar Assistant
        </div>
    </div>
</template>
<script>
import { marked } from 'marked';
import ApiRequests from '@/ApiRequests';

export default {
    data() {
        return {
            cocktail: {},
            printReady: false
        }
    },
    computed: {
        parsedDescription() {
            if (!this.cocktail.description) {
                return null;
            }

            return marked.parse(this.cocktail.description)
        },
        parsedInstructions() {
            if (!this.cocktail.instructions) {
                return null;
            }

            return marked.parse(this.cocktail.instructions)
        },
    },
    created() {
        ApiRequests.fetchCocktail(this.$route.params.id).then(data => {
            this.cocktail = data
            this.printReady = true
        }).catch(e => {
            this.$toast.error(e.message);
        })
    }
}
</script>

<style scoped>
.cocktail-print-container {
    color: #000;
    font-size: 0.7rem;
    border: 2px dotted #000;
    padding: 10px;
    background-color: #fff;
    margin: 20px auto;
    max-width: 700px;
}

h1 {
    border-bottom: 3px double #333;
    text-align: center;
}

h2 {
    font-size: 1rem;
    font-weight: bold;
}

ul, ol {
    padding-left: 15px;
}

.print-second-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    column-gap: 30px;
}

.print-ingredients {
    border: 1px solid #333;
    padding: 10px;
}

.cocktail-print-image img {
    max-height: 200px;
    display: block;
    margin: 20px auto;
}

.cocktail-print-footer {
    text-align: center;
    font-size: 0.6rem;
    margin-top: 10px;
}
</style>
