<template>
    <div class="list-print-container">
        <h3>{{ $t('your-shopping-list') }}</h3>
        <ul>
            <li v-for="ingredient in list" :key="ingredient.id">
                <div class="checkbox"></div>
                <div class="name">
                    {{ ingredient.ingredient.name }} x{{ ingredient.quantity }}
                </div>
            </li>
        </ul>
        <div class="list-print-footer">
            Generated by Bar Assistant
        </div>
    </div>
</template>
<script>
import AppState from '@/AppState.js';
import BarAssistantClient from '@/api/BarAssistantClient';

export default {
    data() {
        return {
            appState: new AppState(),
            list: {},
            printReady: false
        }
    },
    created() {
        BarAssistantClient.getShoppingList(this.appState.user.id).then(response => {
            this.list = response.data
            this.printReady = true

            this.$nextTick(() => {
                window.print();
            })

            window.addEventListener('afterprint', () => {
                this.$nextTick(() => {
                    window.close();
                })
            })
        }).catch(e => {
            this.$toast.error(e.message)
        })
    }
}
</script>

<style scoped>
.list-print-container {
    color: #000;
    font-size: 0.7rem;
    border: 1px dotted #000;
    padding: 10px;
    background-color: #fff;
    margin: 20px auto;
    max-width: 700px;
}

.list-print-container ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: grid;
    grid-template-columns: 1fr 1fr;
}

.list-print-container ul li {
    display: flex;
    align-items: center;
    gap: var(--gap-size-2);
    margin-bottom: 10px;
}

h3 {
    border-bottom: 3px double #333;
    text-align: center;
    font-family: var(--font-heading);
    font-size: 1.5rem;
    margin-bottom: 20px;
}

.checkbox {
    width: 25px;
    height: 25px;
    border: 2px solid #000;
    flex-grow: 0;
    flex-shrink: 0;
}

.list-print-footer {
    text-align: center;
    font-size: 0.6rem;
    margin-top: 10px;
}
</style>
