<template>
    <div class="cocktail-print-container">
        <div class="print-first-row">
            <div v-if="cocktail.images && cocktail.images.length > 0" class="cocktail-print-image">
                <img :src="cocktail.images[0].url" :alt="cocktail.images[0].copyright">
                <span>© {{ cocktail.images[0].copyright }}</span>
            </div>
            <div class="cocktail-main-info">
                <h1>{{ cocktail.name }}</h1>
                <template v-if="cocktail.description">
                    <h2>{{ $t('description') }}:</h2>
                    <div v-html="parsedDescription"></div>
                </template>
            </div>
        </div>
        <div class="print-second-row">
            <div class="print-ingredients">
                <p class="print-ingredients-batch" v-if="targetVolumeToScaleTo">
                    Batch size {{ targetVolumeToScaleTo }} {{ appState.defaultUnit }} ({{ targetVolumeDilution }}% dilution).
                    <template v-if="waterDilution > 0">
                        <br>
                        {{ $t('target-volume-dilution-help', {total: waterDilution + ' ' + appState.defaultUnit}) }}
                    </template>
                </p>
                <h2>{{ $t('ingredient.ingredients') }}:</h2>
                <ul>
                    <li v-for="ingredient in cocktail.ingredients" :key="ingredient.id">
                        <CocktailIngredientShare :cocktail-ingredient="ingredient" :units="appState.defaultUnit" :scale-factor="scaleFactor"></CocktailIngredientShare>
                    </li>
                </ul>
            </div>
            <div class="print-instructions">
                <h2>{{ $t('instructions') }}:</h2>
                <div v-html="parsedInstructions"></div>
                <template v-if="cocktail.garnish">
                    <h2>{{ $t('garnish') }}:</h2>
                    <div v-html="parsedGarnish"></div>
                </template>
            </div>
        </div>
        <div class="cocktail-print-footer">
            Generated by Bar Assistant
        </div>
    </div>
</template>
<script>
import {micromark} from 'micromark'
import BarAssistantClient from '@/api/BarAssistantClient'
import AppState from '../../AppState'
import UnitHandler from '../../UnitHandler'
import CocktailIngredientShare from '../Cocktail/CocktailIngredientShare.vue'

export default {
    components: {CocktailIngredientShare},
    data() {
        return {
            appState: new AppState(),
            cocktail: {},
            scaleFactor: 1,
            targetVolumeToScaleTo: null,
            targetVolumeDilution: 0,
            waterDilution: 0,
            printReady: false
        }
    },
    computed: {
        parsedDescription() {
            if (!this.cocktail.description) {
                return null
            }

            return micromark(this.cocktail.description)
        },
        parsedInstructions() {
            if (!this.cocktail.instructions) {
                return null
            }

            return micromark(this.cocktail.instructions)
        },
        parsedGarnish() {
            if (!this.cocktail.garnish) {
                return null
            }

            return micromark(this.cocktail.garnish)
        },
    },
    created() {
        this.scaleFactor = this.$route.query.scaleFactor ?? 1
        this.targetVolumeToScaleTo = this.$route.query.targetVolumeToScaleTo ?? null
        this.targetVolumeDilution = this.$route.query.targetVolumeDilution ?? 0
        this.waterDilution = this.$route.query.waterDilution ?? 0
        BarAssistantClient.getCocktail(this.$route.params.id).then(resp => {
            this.cocktail = resp.data
            this.printReady = true
            this.$nextTick(() => {
                window.print();
            })

            window.addEventListener('afterprint', () => {
                this.$nextTick(() => {
                    window.close();
                })
            })
        }).catch(e => {
            this.$toast.error(e.message)
        })
    },
    methods: {
        ingredientAmount(ing) {
            const appState = new AppState()
            const defaultUnit = appState.defaultUnit

            return UnitHandler.print(ing, defaultUnit)
        }
    }
}
</script>

<style>
.cocktail-print-container {
    color: #000;
    font-size: 0.7rem;
    border: 1px dotted #000;
    padding: 10px;
    background-color: #fff;
    margin: 20px auto;
    /* max-width: 500px; */
}

.print-first-row {
    display: grid;
    grid-template-columns: 1fr 2fr;
}

h1 {
    border-bottom: 3px double #333;
    text-align: center;
    font-family: var(--font-heading);
    font-size: 1.5rem;
}

h2 {
    font-size: 0.8rem;
    font-weight: var(--fw-bold);
}

ul, ol {
    padding-left: 15px;
}

.print-instructions :deep(ol) {
    padding-left: 15px;
}

.print-second-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    column-gap: 30px;
    border-top: 3px double #333;
    margin-top: 15px;
    padding-top: 15px;
}

.print-ingredients {
    border: 1px solid #333;
    padding: 10px;
}

.print-ingredients ul {
    list-style: none;
    padding: 0;
}

.print-ingredients .cocktail-ingredient-share__ingredient-substitutes {
    font-size: 0.5rem;
}

.cocktail-print-image {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
}

.cocktail-print-image img {
    padding: 10px;
    padding-bottom: 2px;
    max-height: 300px;
    max-width: 300px;
    display: block;
}

.cocktail-print-footer {
    text-align: center;
    font-size: 0.45rem;
    margin-top: 10px;
}

.print-ingredients-batch {
    border: 1px dashed #000;
    padding: 10px;
}
</style>
