<template>
    <div class="cocktail-print-container">
        <div class="print-first-row">
            <div v-if="cocktail.main_image_id" class="cocktail-print-image">
                <img :src="cocktail.images[0].url" :alt="cocktail.images[0].copyright">
            </div>
            <div class="cocktail-main-info">
                <h1>{{ cocktail.name }}</h1>
                <template v-if="cocktail.description">
                    <h2>{{ $t('description') }}:</h2>
                    <div v-html="parsedDescription"></div>
                </template>
            </div>
        </div>
        <div class="print-second-row">
            <div class="print-ingredients">
                <h2>{{ $t('ingredients') }}:</h2>
                <ul>
                    <li v-for="ingredient in cocktail.ingredients" :key="ingredient.id">
                        {{ ingredientAmount(ingredient) }} &middot; {{ ingredient.name }}
                        <i v-if="ingredient.optional">({{ $t('optional') }})</i>
                    </li>
                </ul>
            </div>
            <div class="print-instructions">
                <h2>{{ $t('instructions') }}:</h2>
                <div v-html="parsedInstructions"></div>
                <template v-if="cocktail.garnish">
                    <h2>{{ $t('garnish') }}:</h2>
                    <div v-html="parsedGarnish"></div>
                </template>
            </div>
        </div>
        <div class="cocktail-print-footer">
            Generated by Bar Assistant
        </div>
    </div>
</template>
<script>
import {micromark} from 'micromark'
import ApiRequests from '@/ApiRequests'
import Utils from '@/Utils'
import AppState from './../../AppState'
import UnitHandler from '../../UnitHandler'

export default {
    data() {
        return {
            cocktail: {},
            printReady: false
        }
    },
    computed: {
        parsedDescription() {
            if (!this.cocktail.description) {
                return null
            }

            return micromark(this.cocktail.description)
        },
        parsedInstructions() {
            if (!this.cocktail.instructions) {
                return null
            }

            return micromark(this.cocktail.instructions)
        },
        parsedGarnish() {
            if (!this.cocktail.garnish) {
                return null
            }

            return micromark(this.cocktail.garnish)
        },
    },
    created() {
        window.addEventListener('afterprint', () => {
            window.close()
        })

        ApiRequests.fetchCocktail(this.$route.params.id).then(data => {
            this.cocktail = data
            this.printReady = true
            // this.$nextTick(() => {
            //     window.print();
            // })
        }).catch(e => {
            this.$toast.error(e.message)
        })
    },
    methods: {
        ingredientAmount(ing) {
            const appState = new AppState()
            const defaultUnit = appState.defaultUnit

            return UnitHandler.print(ing, defaultUnit)
        }
    }
}
</script>

<style scoped>
.cocktail-print-container {
    color: #000;
    font-size: 0.7rem;
    border: 1px dotted #000;
    padding: 10px;
    background-color: #fff;
    margin: 20px auto;
    /* max-width: 500px; */
}

.print-first-row {
    display: grid;
    grid-template-columns: 1fr 2fr;
}

h1 {
    border-bottom: 3px double #333;
    text-align: center;
    font-family: var(--font-heading);
    font-size: 1.5rem;
}

h2 {
    font-size: 0.8rem;
    font-weight: bold;
}

ul, ol {
    padding-left: 15px;
}

.print-instructions :deep(ol) {
    padding-left: 15px;
}

.print-second-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    column-gap: 30px;
    border-top: 3px double #333;
    margin-top: 15px;
    padding-top: 15px;
}

.print-ingredients {
    border: 1px solid #333;
    padding: 10px;
}

.cocktail-print-image {
    display: flex;
    align-items: center;
    justify-content: center;
}

.cocktail-print-image img {
    padding: 10px;
    max-height: 300px;
    max-width: 300px;
    display: block;
}

.cocktail-print-footer {
    text-align: center;
    font-size: 0.45rem;
    margin-top: 10px;
}
</style>
