<template>
    <div class="cocktail-print-container">
        <div class="print-first-row">
            <div v-if="cocktail.images && cocktail.images.length > 0" class="cocktail-print-image">
                <img :src="cocktail.images[0].url" :alt="cocktail.images[0].copyright ?? ''">
                <span v-if="cocktail.images[0].copyright">© {{ cocktail.images[0].copyright }}</span>
            </div>
            <div class="cocktail-main-info">
                <h1>{{ cocktail.name }}</h1>
                <template v-if="cocktail.description">
                    <h2>{{ $t('description') }}:</h2>
                    <div v-html="parsedDescription"></div>
                </template>
            </div>
        </div>
        <div class="print-second-row">
            <div class="print-ingredients">
                <p class="print-ingredients-batch" v-if="targetVolumeToScaleTo">
                    Batch size {{ targetVolumeToScaleTo }} {{ units }} ({{ targetVolumeDilution }}% dilution).
                    <template v-if="waterDilution">
                        <br>
                        {{ $t('target-volume-dilution-help', {total: waterDilution + ' ' + units}) }}
                    </template>
                </p>
                <h2>{{ $t('ingredient.ingredients') }}:</h2>
                <ul>
                    <li v-for="(ingredient, index) in cocktail.ingredients" :key="index">
                        <div class="cocktail-ingredient-share" itemprop="recipeIngredient" :content="ingredient.name + ' - ' + ingredientAmount(ingredient)">
                            <div class="cocktail-ingredient-share__ingredient-name">
                                <span>{{ ingredient.name }} <template v-if="ingredient.optional">({{ $t('optional') }})</template></span>
                                <span v-if="ingredient.substitutes.length > 0" class="cocktail-ingredient-share__ingredient-substitutes">
                                    {{ $t('substitutes') }}: {{ substitutes(ingredient) }}
                                </span>
                            </div>
                            <div class="cocktail-ingredient-share__ingredient-amount">{{ ingredientAmount(ingredient) }}</div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="print-instructions">
                <h2>{{ $t('instructions') }}:</h2>
                <div v-html="parsedInstructions"></div>
                <template v-if="cocktail.garnish">
                    <h2>{{ $t('garnish') }}:</h2>
                    <div v-html="parsedGarnish"></div>
                </template>
            </div>
        </div>
        <div class="cocktail-print-footer">
            Generated by Bar Assistant
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRoute } from 'vue-router'
import { micromark } from 'micromark'
import BarAssistantClient from '@/api/BarAssistantClient'
import AppState from '@/AppState'
import { unitHandler } from '@/composables/useUnits'
import type { components } from '@/api/api'

type Cocktail = components['schemas']['PublicCocktailResource']

const route = useRoute()
const appState = new AppState()
const cocktail = ref<Cocktail>({} as Cocktail)
const scaleFactor = ref(1)
const units = ref(appState.defaultUnit)
const targetVolumeToScaleTo = ref<number | null>(null)
const targetVolumeDilution = ref(0)
const waterDilution = ref<string | null>(null)
const printReady = ref(false)

scaleFactor.value = parseFloat(route.query.scaleFactor as string) || 1
units.value = (route.query.units as string) || appState.defaultUnit
targetVolumeToScaleTo.value = route.query.targetVolumeToScaleTo ? Number(route.query.targetVolumeToScaleTo) : null
targetVolumeDilution.value = Number(route.query.targetVolumeDilution) || 0
waterDilution.value = (route.query.waterDilution as string) || null

const barId = route.params.barId.toString()
const slug = route.params.slug.toString()

BarAssistantClient.getPublicBarCocktail(barId, slug).then(resp => {
    if (resp?.data) {
        cocktail.value = resp.data
    }
    printReady.value = true
    setTimeout(() => {
        window.print()
    }, 500)

    window.addEventListener('afterprint', () => {
        window.close()
    })
}).catch(e => {
    console.error('Failed to fetch cocktail for print:', e)
})

const parsedDescription = computed(() => {
    if (!cocktail.value.description) {
        return null
    }
    return micromark(cocktail.value.description)
})

const parsedInstructions = computed(() => {
    if (!cocktail.value.instructions) {
        return null
    }
    return micromark(cocktail.value.instructions)
})

const parsedGarnish = computed(() => {
    if (!cocktail.value.garnish) {
        return null
    }
    return micromark(cocktail.value.garnish)
})

function ingredientAmount(ing: Cocktail['ingredients'][0]) {
    return unitHandler.print({
        amount: ing.amount,
        amount_max: ing.amount_max,
        units: ing.units,
    }, units.value, scaleFactor.value)
}

function substitutes(ing: Cocktail['ingredients'][0]) {
    return ing.substitutes.map(sub => {
        return `${sub.name} ${unitHandler.print({
            amount: sub.amount,
            amount_max: sub.amount_max,
            units: sub.units,
        }, units.value, scaleFactor.value)}`.trim()
    }).join(', ')
}
</script>

<style>
.cocktail-print-container {
    color: #000;
    font-size: 0.7rem;
    border: 1px dotted #000;
    padding: 10px;
    background-color: #fff;
    margin: 20px auto;
}

.print-first-row {
    display: grid;
    grid-template-columns: 1fr 2fr;
}

h1 {
    border-bottom: 3px double #333;
    text-align: center;
    font-family: var(--font-heading);
    font-size: 1.5rem;
}

h2 {
    font-size: 0.8rem;
    font-weight: var(--fw-bold);
}

ul, ol {
    padding-left: 15px;
}

.print-instructions :deep(ol) {
    padding-left: 15px;
}

.print-second-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    column-gap: 30px;
    border-top: 3px double #333;
    margin-top: 15px;
    padding-top: 15px;
}

.print-ingredients {
    border: 1px solid #333;
    padding: 10px;
}

.print-ingredients ul {
    list-style: none;
    padding: 0;
}

.print-ingredients .cocktail-ingredient-share__ingredient-substitutes {
    font-size: 0.5rem;
}

.cocktail-print-image {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
}

.cocktail-print-image img {
    padding: 10px;
    padding-bottom: 2px;
    max-height: 300px;
    max-width: 300px;
    display: block;
}

.cocktail-print-footer {
    text-align: center;
    font-size: 0.45rem;
    margin-top: 10px;
}

.print-ingredients-batch {
    border: 1px dashed #000;
    padding: 10px;
}

.cocktail-ingredient-share {
    padding: var(--gap-size-1, 4px) 0;
    border-bottom: 1px dotted var(--clr-gray-300, #ccc);
    margin-bottom: var(--gap-size-1, 4px);
    display: flex;
}

.cocktail-ingredient-share__ingredient-name {
    display: flex;
    flex-direction: column;
}

.cocktail-ingredient-share__ingredient-substitutes {
    font-size: 0.75rem;
    color: var(--clr-gray-500, #666);
}

.cocktail-ingredient-share__ingredient-amount {
    font-weight: var(--fw-bold);
    margin-left: auto;
    flex-shrink: 0;
    text-align: right;
}
</style>