<template>
    <div class="list-print-container">
        <h3>Shopping list</h3>
        <ul>
            <li v-for="ingredient in list">
                <div class="checkbox"></div>
                <div class="name">
                    {{ ingredient.name }}
                </div>
            </li>
        </ul>
        <div class="list-print-footer">
            Generated by Bar Assistant
        </div>
    </div>
</template>
<script>
import ApiRequests from '@/ApiRequests';

export default {
    data() {
        return {
            list: {},
            printReady: false
        }
    },
    created() {
        window.addEventListener('afterprint', (e) => {
            window.close();
        });

        ApiRequests.fetchIngredientsOnShoppingList().then(data => {
            this.list = data
            this.printReady = true
        }).catch(e => {
            this.$toast.error(e.message);
        })
    }
}
</script>

<style scoped>
.list-print-container {
    color: #000;
    font-size: 0.7rem;
    border: 1px dotted #000;
    padding: 10px;
    background-color: #fff;
    margin: 20px auto;
    max-width: 700px;
}

.list-print-container ul {
    list-style: none;
    margin: 0;
    padding: 0;
}

.list-print-container ul li {
    display: flex;
    gap: 10px;
    margin-bottom: 10px;
}

.checkbox {
    width: 25px;
    height: 25px;
    border: 1px solid #000;
    flex-grow: 0;
    flex-shrink: 0;
}
</style>
