<template>
    <div ref="recipe" class="public-cocktail-recipe" itemscope itemtype="http://schema.org/Recipe">
        <div class="public-cocktail-recipe__image" itemprop="image" :content="mainImage.url" :style="{ 'background-image': 'url(' + mainImage.url + ')' }">
            <div v-if="mainImage.copyright" class="public-cocktail-recipe__image__copyright">
                {{ $t("imageupload.copyright-notice", { copyright: mainImage.copyright }) }}
            </div>
        </div>
        <div class="public-cocktail-recipe__summary">
            <h2 itemprop="name">{{ cocktail.name }}</h2>
            <div v-show="!!cocktail.description" itemprop="description" class="public-cocktail-recipe__content" v-html="parsedDescription"></div>
            <div v-show="hideUnits == false" class="public-cocktail-recipe__units">
                <button type="button" class="button button--public" :class="{ 'button--active': currentUnit == 'ml' }" @click="currentUnit = 'ml'">ml</button>
                <button type="button" class="button button--public" :class="{ 'button--active': currentUnit == 'oz' }" @click="currentUnit = 'oz'">oz</button>
                <button type="button" class="button button--public" :class="{ 'button--active': currentUnit == 'cl' }" @click="currentUnit = 'cl'">cl</button>
            </div>
            <div class="public-cocktail-recipe__summary__section">
                <h3>{{ $t("ingredient.ingredients") }}</h3>
                <ul>
                    <li v-for="ing in cocktail.ingredients" :key="ing.id">
                        <CocktailIngredientShare :cocktail-ingredient="ing" :units="currentUnit"></CocktailIngredientShare>
                    </li>
                </ul>
            </div>
            <div class="public-cocktail-recipe__summary__section">
                <h3>{{ $t("instructions") }}</h3>
                <div itemprop="recipeInstructions" class="public-cocktail-recipe__content" v-html="parsedInstructions"></div>
            </div>
            <div v-show="!!cocktail.garnish" class="public-cocktail-recipe__summary__section">
                <h3>{{ $t("garnish") }}</h3>
                <div class="public-cocktail-recipe__content" v-html="parsedGarnish"></div>
            </div>
        </div>
    </div>
    <div v-show="!hideFooter" class="generate-image-footer">Generated by <span>barassistant.app</span></div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { micromark } from "micromark";
import AppState from "@/AppState";
import CocktailIngredientShare from "@/components/Cocktail/CocktailIngredientShare.vue";

type RecipeImage = { url?: string | null; copyright?: string | null };
type RecipeCocktail = {
    name?: string;
    description?: string | null;
    instructions?: string | null;
    garnish?: string | null;
    images?: RecipeImage[];
    ingredients?: unknown[];
    bar?: Record<string, unknown>;
};

const props = withDefaults(defineProps<{ cocktail?: RecipeCocktail; hideUnits?: boolean; hideHeader?: boolean; hideFooter?: boolean }>(), {
    cocktail: () => ({
        bar: {},
        images: [],
    }),
    hideUnits: false,
    hideHeader: true,
    hideFooter: true,
});

const appState = new AppState();
const currentUnit = ref<string>("ml");

currentUnit.value = appState.defaultUnit;

const mainImage = computed<RecipeImage>(() => {
    if (props.cocktail && props.cocktail.images && props.cocktail.images.length > 0) {
        return props.cocktail.images[0];
    }

    return {
        url: "/no-cocktail.jpg",
        copyright: null,
    };
});

const parsedDescription = computed(() => {
    if (!props.cocktail.description) {
        return null;
    }

    return micromark(props.cocktail.description);
});

const parsedInstructions = computed(() => {
    if (!props.cocktail.instructions) {
        return null;
    }

    return micromark(props.cocktail.instructions);
});

const parsedGarnish = computed(() => {
    if (!props.cocktail.garnish) {
        return null;
    }

    return micromark(props.cocktail.garnish);
});
</script>

<style scoped>
.public-cocktail-recipe {
    --clr-content-bg: var(--clr-gray-50);
    --clr-content: var(--clr-gray-600);
    --clr-marker: var(--clr-accent-800);
    display: grid;
    grid-template-columns: 1fr 1fr;
    place-content: center;
    margin-inline: auto;
    background: var(--clr-content-bg);
    border-radius: var(--radius-3);
    overflow: hidden;
    box-shadow: var(--shadow-elevation-medium-dark);
    align-items: start;
}

.dark-theme .public-cocktail-recipe {
    --clr-content-bg: linear-gradient(160deg, var(--clr-gray-900) -15%, var(--clr-gray-950) 80%);
    --clr-content: var(--clr-gray-200);
    --shadow-color: 239deg 15% 5%;
    --clr-marker: var(--clr-accent-400);
    border-top: 1px solid var(--clr-gray-800);
}

@media (max-width: 700px) {
    .public-page .public-cocktail-recipe {
        grid-template-columns: 1fr;
    }
}

.public-cocktail-recipe__image {
    position: relative;
    background-position: center;
    background-size: cover;
    height: 100%;
    min-height: 600px;
}

.public-cocktail-recipe__image__copyright {
    position: absolute;
    top: 1rem;
    left: 1rem;
    display: inline-block;
    background-color: rgba(0, 0, 0, 0.4);
    color: #fff;
    border-radius: var(--radius-3);
    padding: 2px 7px;
    font-size: 0.7rem;
    z-index: 2;
}

.public-cocktail-recipe h2 {
    font-size: 3rem;
    font-weight: var(--fw-bold);
    line-height: 1.2;
    font-family: var(--font-heading);
}

.public-cocktail-recipe__summary {
    padding: 2rem;
    display: flex;
    flex-direction: column;
    gap: var(--gap-size-3);
}

.public-cocktail-recipe__summary h3 {
    font-size: 0.75rem;
    letter-spacing: 1px;
    font-weight: var(--fw-bold);
    color: var(--clr-accent-600);
    text-transform: uppercase;
    margin-bottom: 0.5rem;
}

.public-cocktail-recipe__content {
    color: var(--clr-content);
}

:deep(.public-cocktail-recipe__summary ol) {
    padding-left: 18px;
    color: var(--clr-content);
    width: 100%;
}

:deep(.public-cocktail-recipe__summary ol li::marker) {
    color: var(--clr-marker);
}

.public-cocktail-recipe__summary ul {
    padding: 0;
    width: 100%;
    list-style: none;
}

.public-cocktail-recipe__units {
    text-align: right;
}

.generate-image-header {
    margin-bottom: 1rem;
}

.generate-image-footer {
    margin-top: 0.15rem;
    font-size: 0.5rem;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: rgba(255, 255, 255, 0.3);
}

.generate-image-footer span {
    text-decoration: underline;
}
</style>
